# Generated by Django 3.0.7 on 2021-05-01 10:38

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('is_collect_email_addresses', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('question', models.CharField(max_length=256)),
                ('question_type', models.CharField(choices=[('SHORT', 'Short Answer'), ('PARAG', 'Paragraph'), ('MULTI', 'Multiple Choice'), ('CHECK', 'Checkboxes'), ('DROPD', 'Dropdown')], max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('configuration', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.CharField(blank=True, max_length=64, null=True)),
                ('responded_on', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponseAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Survey')),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SurveyQuestion')),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SurveyResponse')),
            ],
        ),
    ]
