version: '2'

services:
  postgres:
    image: postgres:11.6

  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=production
    image: web
    build:
      context: ./
      dockerfile: Dockerfile-prod
    volumes:
      - ./:/code
    ports:
      - "80:8080"
    depends_on:
      - postgres
    command: [
      "gunicorn",
      "--bind", "0.0.0.0:8080",
      "--workers", "10",
      "--access-logfile", "-",
      "surveydo-server.wsgi:application"]
